---
title: Explore cognition structure
author: Liang Zhang
date: "2021-04-27"
output: 
  html_document:
    theme: readable
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(gt)
knitr::opts_knit$set(root.dir = here::here())
```

```{r load-high-level-data}
games_included <- targets::tar_read(games_included) %>% 
  arrange(prep_fun_name, game_name)
targets::tar_load(rmd_child_check_index)
```

# Age development and Reliability

```{r render-age-dev, results='asis'}
for (row in seq_len(nrow(games_included))) {
  cur_game_info <- slice(games_included, row)
  knitr::knit_expand(rmd_child_check_index) %>% 
    knitr::knit(text = ., quiet = TRUE) %>% 
    cat()
  cat("\n\n")
}
```

# Use Full Dataset (with invalid users)

```{r prepare-and-verify-complete-data-full, eval=FALSE}
data <- targets::tar_read(indices_efa_full) %>% 
  select(-user_id)
kmo <- psych::KMO(data)
kmo_vec <- c(ALL = kmo$MSA, kmo$MSAi)
as_tibble_row(kmo_vec) %>% 
  pivot_longer(everything()) %>% 
  kbl(
    digits = 2,
    col.names = c("Index", "Measure of Sampling Adequacy"),
    caption = "KMO measures of sampling adequacy"
  ) %>% 
  kable_classic(full_width = F, html_font = "Source Sans Pro") %>% 
  column_spec(2, color = spec_color(
    findInterval(kmo_vec, seq(0.5, 1, 0.1)), 
    option = "E", direction = -1
  ))
```

```{r explore-on-complete-data-full, eval=FALSE}
psych::vss(data, n = 20, plot = FALSE)
cog_struct <- psych::fa(data, nfactors = 5)
cog_struct
loadings_struct <- as_tibble(unclass(cog_struct$loadings), rownames = "index")
```

```{r visualize-complete-data, fig.height=20, fig.width=9, eval=FALSE}
loadings_struct %>% 
  arrange(across(starts_with("MR"), ~ (abs(.x) > 0.4) * abs(.x))) %>% 
  mutate(index = as_factor(index)) %>% 
  pivot_longer(-index, names_to = "factor", values_to = "loading") %>% 
  ggplot(aes(factor, index, fill = loading)) +
  geom_tile() +
  scale_fill_viridis_c() +
  coord_fixed() +
  labs(x = "", y = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Use Valid Dataset (with valid users only)

```{r prepare-and-verify-data-valid, eval=FALSE}
data <- targets::tar_read(indices_efa_valid) %>% 
  select(-user_id)
kmo <- psych::KMO(data)
kmo_vec <- c(ALL = kmo$MSA, kmo$MSAi)
as_tibble_row(kmo_vec) %>% 
  pivot_longer(everything()) %>% 
  kbl(
    digits = 2,
    col.names = c("Index", "Measure of Sampling Adequacy"),
    caption = "KMO measures of sampling adequacy"
  ) %>% 
  kable_classic(full_width = F, html_font = "Source Sans Pro") %>% 
  column_spec(2, color = spec_color(
    findInterval(kmo_vec, seq(0.5, 1, 0.1)), 
    option = "E", direction = -1
  ))
```

```{r explore-on-data-valid, eval=FALSE}
psych::vss(data, n = 20, plot = FALSE)
cog_struct <- psych::fa(data, nfactors = 5)
cog_struct
loadings_struct <- as_tibble(unclass(cog_struct$loadings), rownames = "index")
```

```{r visualize-data-valid, fig.height=20, fig.width=8, eval=FALSE}
loadings_struct %>% 
  arrange(across(starts_with("MR"), ~ (abs(.x) > 0.4) * abs(.x))) %>% 
  mutate(index = as_factor(index)) %>% 
  pivot_longer(-index, names_to = "factor", values_to = "loading") %>% 
  ggplot(aes(factor, index, fill = loading)) +
  geom_tile() +
  scale_fill_viridis_c() +
  coord_fixed() +
  labs(x = "", y = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Use Normal Dataset (no outliers)

```{r prepare-and-verify-data-normal, eval=FALSE}
data <- targets::tar_read(indices_efa_normal) %>% 
  select(-user_id)
kmo <- psych::KMO(data)
kmo_vec <- c(ALL = kmo$MSA, kmo$MSAi)
as_tibble_row(kmo_vec) %>% 
  pivot_longer(everything()) %>% 
  kbl(
    digits = 2,
    col.names = c("Index", "Measure of Sampling Adequacy"),
    caption = "KMO measures of sampling adequacy"
  ) %>% 
  kable_classic(full_width = F, html_font = "Source Sans Pro") %>% 
  column_spec(2, color = spec_color(
    findInterval(kmo_vec, seq(0.5, 1, 0.1)), 
    option = "E", direction = -1
  ))
```

```{r explore-on-data-normal, eval=FALSE}
psych::vss(data, n = 20, plot = FALSE)
cog_struct <- psych::fa(data, nfactors = 4)
cog_struct
loadings_struct <- as_tibble(unclass(cog_struct$loadings), rownames = "index")
```

```{r visualize-data-normal, fig.height=20, fig.width=8, eval=FALSE}
loadings_struct %>% 
  arrange(across(starts_with("MR"), ~ (abs(.x) > 0.4) * abs(.x))) %>% 
  mutate(index = as_factor(index)) %>% 
  pivot_longer(-index, names_to = "factor", values_to = "loading") %>% 
  ggplot(aes(factor, index, fill = loading)) +
  geom_tile() +
  scale_fill_viridis_c() +
  coord_fixed() +
  labs(x = "", y = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
