---
title: "game_evaluation"
author: "Liang Zhang"
date: "2021-05-21"
output:
  workflowr::wflow_html:
    code_folding: hide
bibliography: references.bib
---

```{r setup, include=FALSE}
library(tidyverse)
library(gt)
library(patchwork)
library(ggpubr)
library(lubridate)
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = 'CairoPNG')
```

```{r load-high-level-data}
games_included <- targets::tar_read(games_included) %>%
  arrange(prep_fun_name, game_name)
targets::tar_load(rmd_child_check_index)
targets::tar_load(test_retest_stats)
targets::tar_load(test_retest_stats_strict)
```

# Overall Reliability

```{r tab-reliability}
full_join(
  test_retest_stats |> 
    select(game_id, index, Whole_N = n_no_invalid, Whole_ICC = icc_no_invalid),
  test_retest_stats_strict |> 
    select(game_id, index, Strict_N = n_no_invalid, Strict_ICC = icc_no_invalid),
  by = c("game_id", "index")
) |> 
  left_join(games_included, by = "game_id") |> 
  select(game_name, index, Whole_N, Whole_ICC, Strict_N, Strict_ICC) |> 
  gt(rowname_col = "index", groupname_col = "game_name") |> 
  tab_stubhead(label = "Index Name") |> 
  tab_spanner_delim(delim = "_") |> 
  fmt_number(contains("ICC")) |> 
  tab_options(column_labels.font.weight = "bold")
```

# Age development and Reliability

```{r render-check-main, results='asis'}
knit_text <- \(text, ...) knitr::knit(text = text, ...)
for (row in seq_len(nrow(games_included))) {
  cur_game_info <- slice(games_included, row)
  knitr::knit_expand(rmd_child_check_index) |>
    knit_text(quiet = TRUE) |>
    cat()
  cat("\n\n")
}
```
